"""AgentCore Runtime entrypoint for the Meridian Phase 5 workflow (MeridianWorkflow).

The CDK wiring names the Gateway URL after the gateway (see gateway_url.py), and the backend
modules read AGENTCORE_GATEWAY_URL, so it is mapped before they import. The staged
``backend`` package beside this file is generated by scripts/stage_workflow_runtime.py.
"""

import json
import os

from gateway_url import map_gateway_url

map_gateway_url(os.environ)

from bedrock_agentcore.runtime import BedrockAgentCoreApp  # noqa: E402

from backend.agents.phase_05_workflow.runtime_entry import workflow_turn  # noqa: E402

app = BedrockAgentCoreApp()


@app.entrypoint
async def invoke(payload, context=None):
    """Run one workflow turn and stream its events as JSON."""
    session_id = getattr(context, "session_id", None)
    headers = getattr(context, "request_headers", None)
    async for event in workflow_turn(payload, session_id=session_id, headers=headers):
        yield json.dumps(event, ensure_ascii=False)


if __name__ == "__main__":
    app.run()
