"""AgentCore Runtime entrypoint for the Meridian Phase 5 workflow (MeridianWorkflow).

The CDK wiring names the Gateway URL after the gateway, and the backend modules
read AGENTCORE_GATEWAY_URL, so it is mapped before they import. The staged
``backend`` package beside this file is generated by scripts/stage_workflow_runtime.py.
"""

import json
import os

os.environ.setdefault(
    "AGENTCORE_GATEWAY_URL", os.environ.get("AGENTCORE_GATEWAY_MERIDIAN_AURORA_URL", "")
)

from bedrock_agentcore.runtime import BedrockAgentCoreApp  # noqa: E402

from backend.agents.phase_05_workflow.runtime_entry import workflow_turn  # noqa: E402

app = BedrockAgentCoreApp()


@app.entrypoint
async def invoke(payload, context=None):
    """Run one workflow turn and stream its events as JSON."""
    session_id = getattr(context, "session_id", None)
    async for event in workflow_turn(payload, session_id=session_id):
        yield json.dumps(event, ensure_ascii=False)


if __name__ == "__main__":
    app.run()
